/*
 * Generates seed/seed.sql from the single source of truth in src/data/seed.js,
 * so the D1 demo family and the client demo family can never drift apart.
 *
 *   node scripts/generate-seed.mjs
 *   npm run db:seed        # apply to local D1
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { people, relationships, FAMILY_NAME, DEFAULT_FOCUS } from '../src/data/seed.js';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../seed/seed.sql');

const q = (v) =>
  v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const b = (v) => (v ? 1 : 0);

const FAMILY_ID = 'fam_davies';
const USER_ID = 'u_demo';

const lines = [];
lines.push('-- Generated by scripts/generate-seed.mjs — do not edit by hand.');
lines.push('-- A demo family so Phase 1 is testable immediately.');
lines.push('');
lines.push('DELETE FROM relationship; DELETE FROM person; DELETE FROM family; DELETE FROM user;');
lines.push('');
lines.push(`INSERT INTO family (id, name, created_by) VALUES (${q(FAMILY_ID)}, ${q(FAMILY_NAME)}, ${q(USER_ID)});`);
lines.push('');

for (const p of people) {
  lines.push(
    `INSERT INTO person (id, family_id, display_name, given_names, family_name, maiden_name, ` +
      `birth_date, death_date, is_living, is_deceased, is_minor, gender, birth_place, bio, photo_key, ` +
      `created_by, confidence) VALUES (` +
      [
        q(p.id),
        q(FAMILY_ID),
        q(p.display_name),
        q(p.given_names),
        q(p.family_name),
        q(p.maiden_name),
        q(p.birth_date),
        q(p.death_date),
        b(p.is_living),
        b(p.is_deceased),
        b(p.is_minor),
        q(p.gender),
        q(p.birth_place),
        q(p.bio),
        q(p.photo), // demo faces are external URLs; tree.js passes them through
        q(USER_ID),
        q(p.confidence || 'confirmed'),
      ].join(', ') +
      ');',
  );
}
lines.push('');

for (const r of relationships) {
  lines.push(
    `INSERT INTO relationship (id, family_id, from_person, to_person, type, qualifier, partner_status) VALUES (` +
      [
        q(r.id),
        q(FAMILY_ID),
        q(r.from_person),
        q(r.to_person),
        q(r.type),
        q(r.qualifier),
        q(r.partner_status),
      ].join(', ') +
      ');',
  );
}
lines.push('');

// The demo user claims James (our kin-keeper) as themselves.
lines.push(
  `INSERT INTO user (id, email, person_id, family_id, last_seen) VALUES (` +
    `${q(USER_ID)}, 'demo@bloodline.app', ${q(DEFAULT_FOCUS)}, ${q(FAMILY_ID)}, unixepoch());`,
);
lines.push(`UPDATE person SET claimed_by_user_id = ${q(USER_ID)} WHERE id = ${q(DEFAULT_FOCUS)};`);
lines.push('');

writeFileSync(out, lines.join('\n'));
console.log(`Wrote ${out} — ${people.length} people, ${relationships.length} relationships.`);
