/*
 * Regenerates src/lib/staticViewerAssets.generated.js from the real static
 * viewer files under src/START-HERE.html and src/viewer/ (docs/
 * FULL-ARCHIVE-EXPORT.md §3.2's "viewer/" directory + START-HERE.html).
 *
 * WHY a generated plain-JS module instead of Wrangler's `[[rules]]` text/
 * data module imports (the more common Workers pattern for bundling static
 * assets): this package's own test suite runs these files under PLAIN NODE
 * (`node tests/*.test.mjs`, no esbuild/Wrangler bundling step at all — see
 * every other test file's own header comments on why the logic modules
 * never import `cloudflare:workers`), and Node has no built-in loader for
 * importing `.html`/`.css`/`.woff2` as strings/bytes. A plain JS module
 * with the content pre-encoded as string/base64 constants works identically
 * under Node AND Wrangler's esbuild bundler with zero special configuration
 * — the same reasoning that keeps the rest of this package's logic testable
 * outside the Workers runtime.
 *
 * Run this again whenever START-HERE.html or anything under viewer/
 * changes: `node scripts/generateStaticAssets.mjs`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC_DIR = path.join(__dirname, '../src');
const OUT_FILE = path.join(__dirname, '../src/lib/staticViewerAssets.generated.js');

// archivePath: where this file lands inside the exported ZIP (docs/
// FULL-ARCHIVE-EXPORT.md §3.2's directory layout — START-HERE.html at the
// archive root, everything else under viewer/).
const FILES = [
  { archivePath: 'START-HERE.html', diskPath: 'START-HERE.html', encoding: 'text', mimeType: 'text/html' },
  { archivePath: 'viewer/app.js', diskPath: 'viewer/app.js', encoding: 'text', mimeType: 'application/javascript' },
  { archivePath: 'viewer/styles.css', diskPath: 'viewer/styles.css', encoding: 'text', mimeType: 'text/css' },
  { archivePath: 'viewer/fonts/fraunces-latin-400.woff2', diskPath: 'viewer/fonts/fraunces-latin-400.woff2', encoding: 'base64', mimeType: 'font/woff2' },
  { archivePath: 'viewer/fonts/fraunces-latin-600.woff2', diskPath: 'viewer/fonts/fraunces-latin-600.woff2', encoding: 'base64', mimeType: 'font/woff2' },
  { archivePath: 'viewer/fonts/hanken-grotesk-latin-400.woff2', diskPath: 'viewer/fonts/hanken-grotesk-latin-400.woff2', encoding: 'base64', mimeType: 'font/woff2' },
  { archivePath: 'viewer/fonts/hanken-grotesk-latin-600.woff2', diskPath: 'viewer/fonts/hanken-grotesk-latin-600.woff2', encoding: 'base64', mimeType: 'font/woff2' },
  { archivePath: 'viewer/licenses/Fraunces-OFL.txt', diskPath: 'viewer/licenses/Fraunces-OFL.txt', encoding: 'text', mimeType: 'text/plain' },
  { archivePath: 'viewer/licenses/Hanken-Grotesk-OFL.txt', diskPath: 'viewer/licenses/Hanken-Grotesk-OFL.txt', encoding: 'text', mimeType: 'text/plain' },
];

const entries = FILES.map((f) => {
  const abs = path.join(SRC_DIR, f.diskPath);
  if (f.encoding === 'text') {
    const text = readFileSync(abs, 'utf8');
    return `  { path: ${JSON.stringify(f.archivePath)}, mimeType: ${JSON.stringify(f.mimeType)}, encoding: 'text', content: ${JSON.stringify(text)} }`;
  }
  const base64 = readFileSync(abs).toString('base64');
  return `  { path: ${JSON.stringify(f.archivePath)}, mimeType: ${JSON.stringify(f.mimeType)}, encoding: 'base64', content: ${JSON.stringify(base64)} }`;
});

const out = `/*
 * AUTO-GENERATED by scripts/generateStaticAssets.mjs — do not hand-edit.
 * Regenerate after changing src/START-HERE.html or anything under
 * src/viewer/: \`node scripts/generateStaticAssets.mjs\`.
 */
export const STATIC_VIEWER_FILES = [
${entries.join(',\n')},
];
`;

writeFileSync(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE} (${FILES.length} files)`);
